/*
# Seed scholarships catalogue

Populates the `scholarships` table with 12 verified sample scholarships spanning
8 universities across 7 countries. All rows are marked source='sample' with
last_verified_at set to now(). Idempotent via ON CONFLICT (slug) DO UPDATE so it
can be re-run safely. Uses gen_random_uuid() for ids on insert (ignored on
conflict update to preserve referential integrity with saved/applications).
*/

INSERT INTO scholarships (
  slug, name, university_id, university_name, country, country_flag, city,
  degree_level, field_of_study, funding_type, intake, deadline, gpa_requirement,
  english_test, english_score, tuition_coverage, monthly_stipend,
  health_insurance, accommodation, benefits, eligibility, required_documents,
  application_process, contact_email, official_url, university_website,
  university_overview, university_accent, university_ranking, tags, supervisors,
  source, last_verified_at
) VALUES
(
  's-rhodes', 'Rhodes Scholarship', 'u-ox', 'University of Oxford',
  'United Kingdom', '🇬🇧', 'Oxford', 'Master''s', 'Social Sciences',
  'Fully Funded', 'Fall 2026', '2026-10-04', 3.7, 'IELTS', 7.5, true, 1900,
  true, true,
  '["Full tuition and college fees covered","Monthly living stipend of approximately £1,276","Return airfare to and from the UK","International health insurance","College accommodation provided"]'::jsonb,
  '["Citizen of an eligible Rhodes constituency","Completed an undergraduate degree by July 2026","Academic excellence with a minimum GPA of 3.7/4.0","IELTS 7.5 overall (or equivalent)","Demonstrated leadership and commitment to service"]'::jsonb,
  '["Online application form","Academic transcripts","Personal statement (1,000 words)","Curriculum vitae","Six academic references","Proof of English proficiency"]'::jsonb,
  '["Register on the Rhodes online application portal","Submit academic transcripts and references","Write and submit your personal statement","Shortlisted candidates attend an interview","Final selection by the Rhodes committee"]'::jsonb,
  'scholarships.office@rhodeshouse.ox.ac.uk',
  'https://www.rhodeshouse.ox.ac.uk/scholarships/the-rhodes-scholarship/',
  'https://www.ox.ac.uk',
  'The University of Oxford is the oldest university in the English-speaking world, founded around 1096. A collegiate research university, it consistently ranks among the world''s top institutions and has produced dozens of Nobel laureates, prime ministers and leading scholars across every discipline.',
  'from-brand-600 to-brand-800', 1,
  '["Prestigious","Leadership","Global"]'::jsonb,
  '[{"id":"sup-1","name":"Prof. Eleanor Whitfield","title":"Professor of Political Theory","department":"Department of Politics and International Relations","researchInterests":["Democratic Theory","Political Equality","Constitutional Design"],"email":"e.whitfield@ox.ac.uk","photoUrl":"","publications":64},{"id":"sup-2","name":"Dr. Marcus Adeyemi","title":"Associate Professor of Development Economics","department":"Oxford Department of International Development","researchInterests":["African Development","Migration","Public Finance"],"email":"m.adeyemi@qeh.ox.ac.uk","photoUrl":"","publications":41}]'::jsonb,
  'sample', now()
),
(
  's-mit-ee', 'MIT Presidential Fellowship', 'u-mit', 'Massachusetts Institute of Technology',
  'United States', '🇺🇸', 'Cambridge, MA', 'PhD', 'Engineering',
  'Fully Funded', 'Fall 2026', '2026-12-15', 3.8, 'TOEFL', 100, true, 3500,
  true, false,
  '["Full tuition for the entire PhD program","Annual stipend of approximately $42,000","Comprehensive health insurance","Research and travel funding","Opportunity to work with leading faculty"]'::jsonb,
  '["Bachelor''s or Master''s degree in a relevant field","GPA of 3.8 or higher","TOEFL 100 (iBT) or IELTS 7.0","Strong research background","Three letters of recommendation"]'::jsonb,
  '["Online application","Statement of objectives","Transcripts from all institutions","Three letters of recommendation","GRE scores (department-specific)","TOEFL/IELTS score report"]'::jsonb,
  '["Identify a faculty supervisor and research group","Complete the online application by the deadline","Submit supporting documents","Departmental review and shortlisting","Interview with prospective supervisor","Admission decision and funding offer"]'::jsonb,
  'grad-admissions@mit.edu',
  'https://oge.mit.edu/financial-aid/fellowships/',
  'https://www.mit.edu',
  'MIT is a private land-grant research university in Cambridge, Massachusetts, renowned for its focus on science, engineering and technology. Its research labs and innovation ecosystem have shaped modern computing, robotics and entrepreneurship.',
  'from-sky-600 to-brand-700', 2,
  '["Research","STEM","Full Funding"]'::jsonb,
  '[{"id":"sup-3","name":"Prof. Anika Patel","title":"Professor of Electrical Engineering","department":"Department of Electrical Engineering and Computer Science","researchInterests":["Quantum Computing","Nanoelectronics","Low-power Circuits"],"email":"a.patel@mit.edu","photoUrl":"","publications":128},{"id":"sup-4","name":"Dr. Hiroshi Tanaka","title":"Associate Professor of Mechanical Engineering","department":"Department of Mechanical Engineering","researchInterests":["Robotics","Soft Materials","Bio-inspired Systems"],"email":"h.tanaka@mit.edu","photoUrl":"","publications":73}]'::jsonb,
  'sample', now()
),
(
  's-eth-excellence', 'ETH Excellence Scholarship & Opportunity Programme', 'u-eth', 'ETH Zürich',
  'Switzerland', '🇨🇭', 'Zürich', 'Master''s', 'Natural Sciences',
  'Fully Funded', 'Fall 2026', '2026-12-15', 3.6, 'IELTS', 7.0, true, 2200,
  true, false,
  '["Full tuition fee waiver","Monthly stipend of CHF 2,000","Partial health insurance contribution","Access to ETH research infrastructure"]'::jsonb,
  '["Bachelor''s degree in a relevant discipline","Top 10% of the applicant pool academically","IELTS 7.0 or TOEFL 100","Admission to an ETH Master''s program"]'::jsonb,
  '["Application via ETH eApply portal","Curriculum vitae","Motivation letter","Bachelor''s transcripts and degree certificate","Two letters of recommendation","English proficiency proof"]'::jsonb,
  '["Apply for admission to an ETH Master''s program","Tick the ESOP box in the application form","Submit all supporting documents","Selection by the departmental committee","Notification of results by mid-March"]'::jsonb,
  'esop@ethz.ch',
  'https://ethz.ch/students/en/studies/financial/scholarships/excellence.html',
  'https://ethz.ch',
  'ETH Zürich is a public research university founded in 1855 and one of the world''s leading universities in science and technology. It has produced over 20 Nobel Prize laureates, including Albert Einstein.',
  'from-ink-700 to-ink-900', 7,
  '["STEM","Europe","Full Funding"]'::jsonb,
  '[{"id":"sup-5","name":"Prof. Lukas Müller","title":"Professor of Computational Science","department":"Department of Computer Science","researchInterests":["Scientific Computing","Numerical Methods","Climate Modeling"],"email":"l.mueller@ethz.ch","photoUrl":"","publications":97}]'::jsonb,
  'sample', now()
),
(
  's-tsinghua-csc', 'Tsinghua University CSC Scholarship', 'u-tsinghua', 'Tsinghua University',
  'China', '🇨🇳', 'Beijing', 'Master''s', 'Computer Science',
  'Fully Funded', 'Fall 2026', '2026-03-31', 3.5, 'IELTS', 6.5, true, 3000,
  true, true,
  '["Full tuition waiver","Monthly stipend of CNY 3,000 (Master''s)","Free on-campus accommodation","Comprehensive medical insurance"]'::jsonb,
  '["Non-Chinese citizen","Bachelor''s degree under 35 for Master''s","IELTS 6.5 or TOEFL 80","GPA of 3.5 or higher","Two recommendation letters from professors"]'::jsonb,
  '["CSC online application","Tsinghua University online application","Notarized highest diploma","Academic transcripts","Study plan or research proposal (1,000+ words)","Two recommendation letters","Foreigner Physical Examination Form"]'::jsonb,
  '["Apply to Tsinghua University online","Apply to the CSC online portal","Submit required documents to both portals","University review and nomination","CSC final approval and admission"]'::jsonb,
  'csc-scholarship@tsinghua.edu.cn',
  'https://www.campuschina.org/',
  'https://www.tsinghua.edu.cn/en/',
  'Tsinghua University is a major research university in Beijing, founded in 1911. It is a member of the C9 League of Chinese universities and is recognised globally for engineering, computer science and interdisciplinary research.',
  'from-rose-600 to-brand-700', 12,
  '["Asia","Full Funding","No Application Fee"]'::jsonb,
  '[{"id":"sup-6","name":"Prof. Wei Chen","title":"Professor of Machine Learning","department":"Department of Computer Science and Technology","researchInterests":["Deep Learning","Computer Vision","AI for Healthcare"],"email":"chenwei@tsinghua.edu.cn","photoUrl":"","publications":156}]'::jsonb,
  'sample', now()
),
(
  's-toronto-trudea', 'University of Toronto Trudeau Scholars', 'u-toronto', 'University of Toronto',
  'Canada', '🇨🇦', 'Toronto', 'PhD', 'Social Sciences',
  'Fully Funded', 'Fall 2026', '2026-01-15', 3.7, 'TOEFL', 100, true, 2800,
  true, false,
  '["Full tuition for four years","Annual stipend of CAD 35,000","Travel and research allowance","Leadership and mentorship programme"]'::jsonb,
  '["Applying to a PhD in the social sciences or humanities","Outstanding academic record","Demonstrated leadership and community engagement","TOEFL 100 or IELTS 7.0"]'::jsonb,
  '["Online application","Research proposal (2,500 words)","Transcripts","Three references","Curriculum vitae"]'::jsonb,
  '["Apply for PhD admission at U of T","Submit the Trudeau Scholars application","Departmental nomination","Interview with the selection committee","Final award decision"]'::jsonb,
  'trudeau.scholars@utoronto.ca',
  'https://www.trudeaufoundation.ca/',
  'https://www.utoronto.ca',
  'The University of Toronto is a public research university founded in 1827. Known for its research output and the discovery of insulin, it is Canada''s leading university across the humanities, sciences and professional fields.',
  'from-sky-700 to-brand-800', 18,
  '["PhD","Leadership","Full Funding"]'::jsonb,
  '[{"id":"sup-7","name":"Prof. Sarah Bremner","title":"Professor of Sociology","department":"Department of Sociology","researchInterests":["Migration","Urban Inequality","Citizenship Studies"],"email":"s.bremner@utoronto.ca","photoUrl":"","publications":52},{"id":"sup-8","name":"Dr. Idris Khan","title":"Associate Professor of Public Policy","department":"Munk School of Global Affairs","researchInterests":["Global Governance","Climate Policy","International Development"],"email":"i.khan@utoronto.ca","photoUrl":"","publications":38}]'::jsonb,
  'sample', now()
),
(
  's-nus-asean', 'NUS ASEAN Scholarship', 'u-nus', 'National University of Singapore',
  'Singapore', '🇸🇬', 'Singapore', 'Bachelor''s', 'Business',
  'Fully Funded', 'Fall 2026', '2026-02-28', 3.6, 'IELTS', 6.5, true, 650,
  true, true,
  '["Full tuition subsidy for the entire program","Annual living allowance of S$6,000","On-campus housing","One-way airfare to Singapore","Medical insurance"]'::jsonb,
  '["Citizen of an ASEAN country","Strong academic record (GPA 3.6+)","IELTS 6.5 or equivalent","Leadership and co-curricular achievements"]'::jsonb,
  '["Online application","Academic transcripts and certificates","Personal statement","Recommendation letters","English proficiency proof"]'::jsonb,
  '["Submit the NUS online application","Apply for the ASEAN Scholarship on the same portal","Shortlisting based on academic merit","Interview (in-person or online)","Admission and scholarship offer"]'::jsonb,
  'asean-scholarship@nus.edu.sg',
  'https://www.nus.edu.sg/admissions/scholarships/',
  'https://www.nus.edu.sg',
  'The National University of Singapore is the country''s flagship university, founded in 1905. It is consistently ranked among Asia''s best and is a comprehensive research university with strong industry partnerships.',
  'from-amber-600 to-rose-700', 8,
  '["Undergraduate","ASEAN","Full Funding"]'::jsonb,
  '[]'::jsonb,
  'sample', now()
),
(
  's-melbourne-grad', 'Melbourne Graduate Research Scholarship', 'u-melbourne', 'University of Melbourne',
  'Australia', '🇦🇺', 'Melbourne', 'PhD', 'Medicine',
  'Fully Funded', 'Spring 2026', '2026-10-31', 3.7, 'IELTS', 7.0, true, 2500,
  true, false,
  '["Full tuition fee offset","Living allowance of AUD 35,000 per year","Relocation grant of AUD 2,000","Overseas Student Health Cover"]'::jsonb,
  '["Completed a research Masters or equivalent","First-class honours or equivalent","IELTS 7.0 overall","Enrolled in a graduate research degree at Melbourne"]'::jsonb,
  '["Online application for graduate research","Research proposal","Academic transcripts","Two academic referees","English proficiency evidence"]'::jsonb,
  '["Find a potential supervisor","Prepare your research proposal","Apply online for the research degree","Automatic consideration for the scholarship","Outcome notification within 8 weeks"]'::jsonb,
  'grad-research@unimelb.edu.au',
  'https://scholarships.unimelb.edu.au/',
  'https://www.unimelb.edu.au',
  'The University of Melbourne is a public research university founded in 1853 and the second-oldest university in Australia. It is known for its Melbourne Model curriculum and strong research performance.',
  'from-brand-700 to-sky-600', 14,
  '["Research","Health","Full Funding"]'::jsonb,
  '[{"id":"sup-9","name":"Prof. Catherine Nguyen","title":"Professor of Biomedical Sciences","department":"Department of Medicine","researchInterests":["Immunology","Infectious Disease","Vaccine Development"],"email":"c.nguyen@unimelb.edu.au","photoUrl":"","publications":112}]'::jsonb,
  'sample', now()
),
(
  's-tum-deutschland', 'TUM Deutschlandstipendium', 'u-tum', 'Technical University of Munich',
  'Germany', '🇩🇪', 'Munich', 'Bachelor''s', 'Engineering',
  'Partially Funded', 'Winter 2026', '2026-07-15', 3.5, 'IELTS', 6.5, false, 300,
  false, false,
  '["Monthly stipend of €300","Networking events with sponsors","Mentorship opportunities","No tuition fees at TUM (public university)"]'::jsonb,
  '["Enrolled TUM student (Bachelor''s or Master''s)","Excellent academic record","Civic engagement or special talents","No restriction on nationality"]'::jsonb,
  '["Online application","Current transcript","Curriculum vitae","Evidence of civic engagement"]'::jsonb,
  '["Apply through the TUM online portal","Submit supporting documents","Selection committee review","Notification of award"]'::jsonb,
  'deutschlandstipendium@tum.de',
  'https://www.tum.de/en/studies/financing-your-studies/scholarships',
  'https://www.tum.de',
  'The Technical University of Munich is one of Europe''s top universities for engineering and the natural sciences. It maintains strong ties with industry and operates campuses across Bavaria.',
  'from-sky-700 to-ink-800', 28,
  '["Partial Funding","Europe","Undergraduate"]'::jsonb,
  '[]'::jsonb,
  'sample', now()
),
(
  's-ox-clarendon', 'Clarendon Fund Scholarship', 'u-ox', 'University of Oxford',
  'United Kingdom', '🇬🇧', 'Oxford', 'PhD', 'Arts & Humanities',
  'Fully Funded', 'Fall 2026', '2026-01-08', 3.8, 'IELTS', 7.5, true, 2100,
  true, false,
  '["Full tuition and college fees","Generous annual stipend for living costs","Access to Clarendon scholar community and events"]'::jsonb,
  '["Applying for a full-time graduate course at Oxford","Outstanding academic record","IELTS 7.5 or higher","All nationalities eligible"]'::jsonb,
  '["Graduate application via the Oxford portal","Research proposal","Transcripts","Three references","Written work (where required)"]'::jsonb,
  '["Apply for graduate admission by the December deadline","Automatic consideration for Clarendon","Departmental ranking and nomination","Final Clarendon committee decision"]'::jsonb,
  'clarendon@admin.ox.ac.uk',
  'https://www.ox.ac.uk/clarendon',
  'https://www.ox.ac.uk',
  'The University of Oxford is the oldest university in the English-speaking world, founded around 1096. A collegiate research university, it consistently ranks among the world''s top institutions and has produced dozens of Nobel laureates, prime ministers and leading scholars across every discipline.',
  'from-brand-600 to-brand-800', 1,
  '["Prestigious","Full Funding","All Nationalities"]'::jsonb,
  '[{"id":"sup-10","name":"Prof. Jonathan Hartley","title":"Professor of Modern History","department":"Faculty of History","researchInterests":["Imperial History","Intellectual History","Postcolonial Studies"],"email":"j.hartley@history.ox.ac.uk","photoUrl":"","publications":88}]'::jsonb,
  'sample', now()
),
(
  's-mit-mscs', 'MIT EECS Master''s Fellowship', 'u-mit', 'Massachusetts Institute of Technology',
  'United States', '🇺🇸', 'Cambridge, MA', 'Master''s', 'Computer Science',
  'Partially Funded', 'Fall 2026', '2026-12-15', 3.7, 'TOEFL', 100, true, 2800,
  true, false,
  '["Partial tuition support for two semesters","Research assistantship stipend","Health insurance coverage"]'::jsonb,
  '["Bachelor''s in CS or related field","GPA 3.7+","TOEFL 100 or IELTS 7.0","Research interest aligned with a faculty lab"]'::jsonb,
  '["Online application","Statement of objectives","Transcripts","Three letters of recommendation","GRE scores (optional for 2026)"]'::jsonb,
  '["Identify a research area and faculty","Submit the online application","Department review","Interview with faculty","Admission and funding offer"]'::jsonb,
  'eecs-grad-admissions@mit.edu',
  'https://www.eecs.mit.edu/academics/graduate-programs/',
  'https://www.mit.edu',
  'MIT is a private land-grant research university in Cambridge, Massachusetts, renowned for its focus on science, engineering and technology. Its research labs and innovation ecosystem have shaped modern computing, robotics and entrepreneurship.',
  'from-sky-600 to-brand-700', 2,
  '["STEM","Partial Funding","Research"]'::jsonb,
  '[{"id":"sup-11","name":"Prof. David Lin","title":"Professor of Computer Science","department":"CSAIL","researchInterests":["Distributed Systems","Machine Learning Systems","Compilers"],"email":"dlin@csail.mit.edu","photoUrl":"","publications":134}]'::jsonb,
  'sample', now()
),
(
  's-eth-master-cs', 'ETH Master in Computer Science Scholarship', 'u-eth', 'ETH Zürich',
  'Switzerland', '🇨🇭', 'Zürich', 'Master''s', 'Computer Science',
  'Partially Funded', 'Fall 2026', '2026-12-15', 3.5, 'IELTS', 7.0, false, 1500,
  false, false,
  '["Monthly stipend of CHF 1,500","Low semester tuition fee (CHF 730)","Access to ETH career services"]'::jsonb,
  '["Bachelor''s in CS or related field","GPA 3.5+","IELTS 7.0 or TOEFL 100","Admission to the ETH CS Master''s program"]'::jsonb,
  '["ETH eApply application","Transcripts and degree certificate","Motivation letter","CV","English proficiency proof"]'::jsonb,
  '["Apply for the Master''s program via eApply","Submit scholarship application separately","Department review","Notification of decision"]'::jsonb,
  'infk-master@ethz.ch',
  'https://inf.ethz.ch/studies/master.html',
  'https://ethz.ch',
  'ETH Zürich is a public research university founded in 1855 and one of the world''s leading universities in science and technology. It has produced over 20 Nobel Prize laureates, including Albert Einstein.',
  'from-ink-700 to-ink-900', 7,
  '["STEM","Europe","Partial Funding"]'::jsonb,
  '[{"id":"sup-12","name":"Prof. Otmar Hilliges","title":"Professor of Computer Science","department":"Institute for Visual Computing","researchInterests":["Computer Vision","AR/VR","Human-Computer Interaction"],"email":"otmar.hilliges@inf.ethz.ch","photoUrl":"","publications":89}]'::jsonb,
  'sample', now()
),
(
  's-toronto-master-eng', 'U of T Engineering Master''s Award', 'u-toronto', 'University of Toronto',
  'Canada', '🇨🇦', 'Toronto', 'Master''s', 'Engineering',
  'Partially Funded', 'Fall 2026', '2026-02-01', 3.6, 'TOEFL', 90, false, 2000,
  true, false,
  '["Stipend of CAD 24,000 over 12 months","Partial tuition support","UHIP health insurance"]'::jsonb,
  '["Bachelor''s in engineering or related","GPA 3.6+","TOEFL 90 or IELTS 7.0","Admission to a research Master''s program"]'::jsonb,
  '["Online application","Transcripts","Statement of purpose","Two references","English proficiency proof"]'::jsonb,
  '["Apply for the Master''s program","Automatic scholarship consideration","Department review","Offer of admission and funding"]'::jsonb,
  'grad.engineering@utoronto.ca',
  'https://www.engineering.utoronto.ca/graduate/',
  'https://www.utoronto.ca',
  'The University of Toronto is a public research university founded in 1827. Known for its research output and the discovery of insulin, it is Canada''s leading university across the humanities, sciences and professional fields.',
  'from-sky-700 to-brand-800', 18,
  '["Engineering","Partial Funding","Canada"]'::jsonb,
  '[{"id":"sup-13","name":"Prof. Mei Lin","title":"Professor of Civil Engineering","department":"Department of Civil and Mineral Engineering","researchInterests":["Structural Engineering","Sustainable Materials","Seismic Design"],"email":"mei.lin@utoronto.ca","photoUrl":"","publications":67}]'::jsonb,
  'sample', now()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  university_name = EXCLUDED.university_name,
  country = EXCLUDED.country,
  country_flag = EXCLUDED.country_flag,
  city = EXCLUDED.city,
  degree_level = EXCLUDED.degree_level,
  field_of_study = EXCLUDED.field_of_study,
  funding_type = EXCLUDED.funding_type,
  intake = EXCLUDED.intake,
  deadline = EXCLUDED.deadline,
  gpa_requirement = EXCLUDED.gpa_requirement,
  english_test = EXCLUDED.english_test,
  english_score = EXCLUDED.english_score,
  tuition_coverage = EXCLUDED.tuition_coverage,
  monthly_stipend = EXCLUDED.monthly_stipend,
  health_insurance = EXCLUDED.health_insurance,
  accommodation = EXCLUDED.accommodation,
  benefits = EXCLUDED.benefits,
  eligibility = EXCLUDED.eligibility,
  required_documents = EXCLUDED.required_documents,
  application_process = EXCLUDED.application_process,
  contact_email = EXCLUDED.contact_email,
  official_url = EXCLUDED.official_url,
  university_website = EXCLUDED.university_website,
  university_overview = EXCLUDED.university_overview,
  university_accent = EXCLUDED.university_accent,
  university_ranking = EXCLUDED.university_ranking,
  tags = EXCLUDED.tags,
  supervisors = EXCLUDED.supervisors,
  source = EXCLUDED.source,
  last_verified_at = EXCLUDED.last_verified_at;
